controllers:
    resource: ../src/Controller/
    type: attribute

api_login_check:
    path: /api/login_check

get_user:
    path: /api/user
    controller: App\Controller\UserController::getUserData
    methods: [GET]

new_task:
    path: /api/add_task
    controller: App\Controller\UserController::createTask
    methods: [POST]

get_tasks:
    path: /api/get_tasks/{category}
    controller: App\Controller\TaskController::getTasks
    methods: [GET]

get_categories:
    path: /api/get_categories
    controller: App\Controller\CategoryController::getCategories
    methods: [GET]

add_category:
    path: /api/add_category
    controller: App\Controller\CategoryController::addCategory
    methods: [POST]