controllers:
    resource: ../src/Controller/
    type: attribute

#task_save:
#    path: /api/task/save
#    controller: App\Controller\TaskController::index
#    methods: [POST]
#
#new_user:
#    path: /api/user/create
#    controller: App\Controller\UserController::createUser
#    methods: [POST]

api_login_check:
    path: /api/login_check

get_user:
    path: /api/user
    controller: App\Controller\UserController::getUserData
    methods: [GET]
