controllers:
    resource: ../src/Controller/
    type: attribute

api_login_check:
    path: /api/login_check

register:
    path: /api/register
    controller: App\Controller\SecurityController::registerUser
    methods: [POST]

get_user:
    path: /api/user
    controller: App\Controller\UserController::getUserData
    methods: [GET]

new_task:
    path: /api/add_task
    controller: App\Controller\UserController::createTask
    methods: [POST]

get_tasks:
    path: /api/get_tasks/{category}
    controller: App\Controller\TaskController::getTasks
    methods: [GET]

get_categories:
    path: /api/get_categories
    controller: App\Controller\CategoryController::getCategories
    methods: [GET]

add_category:
    path: /api/add_category
    controller: App\Controller\CategoryController::addCategory
    methods: [POST]

change_password:
    path: /api/change_password
    controller: App\Controller\SecurityController::changePassword
    methods: [POST]

delete_category:
    path: /api/delete_category
    controller: App\Controller\CategoryController::deleteCategory
    methods: [POST]

delete_account:
    path: /api/delete_account
    controller: App\Controller\UserController::deleteUser
    methods: [GET]

save_user_data:
    path: /api/save_user
    controller: App\Controller\UserController::saveUserData
    methods: [POST]

delete_task:
    path: /api/delete_task/{id}
    controller: App\Controller\TaskController::deleteTask
    methods: [DELETE]

update_task:
    path: /api/update_task/{id}
    controller: App\Controller\TaskController::updateTask
    methods: [PUT]

save_image:
    path: /api/save_image
    controller: App\Controller\UserController::saveUserImage
    methods: [POST]

get_user_image:
    path: /api/user_image/{id}
    controller: App\Controller\UserController::getUserImage
    methods: [GET]

delete_image:
    path: /api/delete_image
    controller: App\Controller\UserController::deleteUserImage
    methods: [GET]